name: zypher_stack

services:
  postgres:
    image: postgres:15
    container_name: zypher_database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # LOCAL DEVELOPMENT ONLY: Uncomment the ports section to expose Postgres to the host machine
    # ports:
    # - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  backend:
    image: ghcr.io/analiceleite/zypher_backend:v1.0.3
    container_name: zypher_backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PUBLIC_HOST: localhost:8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/analiceleite/zypher_frontend:v1.0.4
    container_name: zypher_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pg_data:
    driver: local